language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: E2HaXuvlboSmKuXzImXU+pVhSNdQufdnro+7jc7TyTU68Px52nmJPp982b5UxQBFceBbYS7ueL6rvk8Qm92HcsoveBwrewOK05G57pwBayjkMntYy6e1ttbbd/I7tYaXgXHGa5QovRlDsRotfTEtTxicsBO0hBVCXlzokr/na+64plPUIgj5OWwmNkGekUiAmrNzzZJl/QLv9sdNtnYFrB5Sid7rPa2y3zhGCsylO8IX4edWpewLx4U4E3+h1CRaq0r85q8LIXOojSBKxWZsAeS3qs9iI4LiMdo1ELcXKClZ6XWJbjvKTppNOBkgFDWvhXUs3hyT4qS1GIIeoZhGH4iRVbR2yqFCqJvGbd9oA+RVdX2BUIn52jF1NlRWS5WsPBZOp5IVpFXJCPEzzG4/pf8OE72y39A6RQ4/IFDnaTTTg/YcDbP0xHP/izjzFSsZgziAlQRXTtoo22M8iSHRpJ3BNihyMwlOnm2l5dm2CuvB4Ep3uJOlZol5JTQUIsfUiiPS1yBPCL1TnfJYXtimcjtiEXwH/bR0ljug2kV7OwezNpDMVSYvoW13Df7RydpgO8pvrk9Rs63zIlHK+6zNM+bKieOdVx8HfZXBxnULQXOGt4LbxbuqUUC97XjGhQi+CKN7+YdLverWyRD3NtgHlbAC9E1rT/kDzS4D/8hywbE=
  - secure: c2dusEkwNcdB2+1+Eiv67YlwvmqzZpyu1RuGFOaTFlkqtBg4nw8soQf7BeJTjN7J7KVvoWsQlfgw8vq8fjk4IRcF/ZT26MTjEPrBm3EIMZnETklEt8WTwPOYPqXjijui/bIm+JpngHDjetgXqxrRBTRN8ymzG/ZPmXpW1KfQL6N/8FJGvkCmCvbMZhZM6nPeaYxpVAntW9endfwels+O4QuUUWuCcwfuvaXu1POlQhkYEmRgRENuTytMPJwC7nPUdeTJdUn76ZK0fMWYJF0PnLYhErYIPbaBueGUsLu6Yz9nflDDfuJjo2az7SJLWsjJUltKFNQi/pnHSNw4GBx6iL4yrpr/r2jFaz4CnP7FyUiUq1/aY6wDzlmKhefhAKwM3SEl/ZQBBkoT9H0iE33FiG8Wprtm+qyjGgrGPZDudqLMER8krc8HIbW4APU7dYTI9rSru/Q+s59W0eLElzbI0Ah1tCtuogxDuEb8M1FDxE0gz6gxwrg9piuc9LuoRa3szCryD4z1nqYDDxiHb7NlJpALi7xLDtrfa1pc7OC8otU/5ZbHJJ67uaQvnR5daUxOPQOdUhB1qm1vP84e+izGG+Pfl1I7y0/lhzct+YDvq4t2RRKgvG5YZqj1I6tTXozhwptb3z94jyapTFl/F2QGnS0990zNe2M61zLwQwIbsRc=
  - secure: Si5+eSxRzlRDLBFGTsm6p4HnsXCyp+vFykYbkqmKYlecSmf/aE8j9EGZboK5tRvHowcdIUKXoOxGytj7pqtcSzHKVpdRvYlOyjko4XUdi40BMnNv93c7QNwwXqPFr7S0sgzgRhj/u4hKFJJvn634mYtwkgq/NPqwOgkkfFEEM2Nb5nJ5dam2D7rvFNd7T3mhoQl1XeGqU1DQzIYvgzCXsJf9ndEgr7qF99qn++ARF8KJ/gmAH5zbV93oO+RV2puUiGcSjPHBWATWAMYMI3wq6N1X9KZppdbfIQ1rLMqIIYHH3QoJVZk+FF3kK8i62J/q0Kz/mbDsaKbbFUHFsHc2dMgarIFETLyKbfj5B7LYyPCjMdJoSAlqf4iPpyDeL7lejOLUKdvlOAWJcL66gzXxAYvxOP1fz3on2SuqV+PoueAyQT/YJYCSLb3xAyFlZOn3Fp9RkahpUa4wK2S1D7qigF7Kih03bBAQ8/E/1km0iPS1nVHMwZi7ndD33Aw0kCWucD4MCT4K5uvfAjY1Wk53mxQBX2XhvvgbR1ZXG5HBAnJYdOXfu0E68KaWwdhS0cgqBO30GS4mtTeOsnPIoYAVZEYUjrog0QVJu7AxMlxAIeqmLJL1IBbZztcXd4II278yLkxKQYH9uIahvX61KCH+AOSQzoXo3nIj9M9gwLPlqng=
