language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: OyYTfDdeJoO5T0Shk6/tX7dRP1iGKY7FzxC2yF0I/0ZvjSl7J+nPZzUY4hRDf7nStbkY1hXwx4n5hmS2zIjleZfKSPZ3y50O5Ciq90w9+dm3PcEiH0at3B8/DEtf5JMoE0xI8h+fRWv3u1AWzt9lCQU4PA5i/hxPUSw+s/6e1asPC/k5sSQU7jU2ahfg/1dppT4MClqMgot0eKLx90+jLOs1qK1kiisfScUi8LlC5rDd1CZZ+Kt8oHalZY0Lc6TQH6k6Tx7NlsrAYHGpwGWkz172iCPXiCQdpess9XB9ge5y0Fa0D/V4D20n/xD94P46HDu2ZI5WA5oFVjzKK/VcFM7O+HdhbwlGDNlmpJZgZoJGmKrAyAeIptQ8o1u8axTvozg94zitCbV31VW49rjO6Cig61VGZtHWxdrn9kg0GAdY0zzOZhVsV0aSEBmDAgCMhM8BJcm9YW8x+jHGwEziozXaptfxZn0aa2ykzhPG50a5Q4ilAcQw6m92M34P8OTnqzEdrwUxJkSTRE1A01vkSzMEEni2Ri2TRC3YojcvusymhikIGNGjsKiTA7txNbb3Edrt++bf1Q3xOl2fcAGVLGlsaygL6edbf+gl/l0eTsjScpwM4bhyoT4xGRvGHiGeR4KFK+QOZD/iGSTf5Fm2T9YFuY/AQ1Zvn2VEEp/juN4=
  - secure: fOPo4ulI1r1X4kLbLTop0UT5NewdaBbc9M32oci4zIeF6rbNBSNh1U5GnA7CyK7kiZbE7xMapc/vJ4241aMJJET1pN1Lh03yfZxmDxa1eMDYf5P7Btk2642l1CTiTFZ3CdW3GLWOfCnIHYcoLV6ZBzaIjnVXY9nroGP2C2ohjcdVB1h6BQOGYTR4RcQ7t78lzK9NYac/9Zhus3DiO/Pas4VgeQTR7TvWKACjvh9pjpUZ+pw/ZJcIBmaAlw/8kEolNF9tmoAKpxFBZmlEkr5yK/TQInu1tryzj5mwXsM3UJdsO32f1XPRAakSdPr1/r1uGQf1nD0OmsvFJROYVQeXB56uYD2a+Rg/iGiP3OLsD6hNWyThBOmjtYU31uNTE4G5vsSl2IvicycaZnCT9GhvLT2WI+YfMkKH6XsnumTM7cCMeYi8ETZ+l9pvWRLtpML+MFqjUlcqUFMaa8Df6CWTQ7ZwyF+P/IiTwwGAkOJsv/z8gQgBtPSRE/zF1YtkqKJ3h4UHOrQ7JwjBUzXU5E7MJmA1YdIqfCQcm78zZo8kh76+P/+lzpCq6FgZ0x/+AHpCkp6k1bkMyjKoi1EoBdV2cFVwpmz5nEyujx4feCOT3FpwkZ+W2XANY77JK7AO5qncVSpmsVRD/8NMwVVQqMmBPxWL09iGpsfmDABvsSu0NQM=
  - secure: zJ7R0q6zUdwHyhC6zVJVn/60Id3cUMim0hqW/DH32ovrTm4TxP81dqgT0LbHTaWcmsxvYettIjjR3d/duqXM4w97lpQzyUBecVFnJ6V3+xaiP18BiVswBmLq4HmN72WL+qBAtbAs3jDknZDSkmczZ9Cy6VykBHoKARAo1TLjor1gN5/MNgTy+ugKjXxhjc6L9EpVcCXsmw+q7hArGCM55Ccm0fHkigfhRoWZl+4WjUL+tcGFgHhgmAMFU20mY6/LaaZdBZziPMOVrMdOooeJbk06uLh80WVNTLyGhIVVdkuwTjGi4Rka3qElevk92/YvOqfSnWiOJCJEX/xKrsNSr7WYUDxFcm76IVm/2zDpd86aOmt4TKIRo7O1mkxWPUaMgta1LVrBwp60EM95/ZZJh1NuEJTUXynKR23sY4pC6oYmIT9wO1ajZ/1DQJLH5Pxi3w34QutyqxfQBntgHAFMPQcVkvrjkoPE3VYZP9IRvX1DEhyLvbB4brtE6IBqtfbdjGjtGOH6aeZV+bfrje52uOOhuXf5FNhszzOfTwate5BH0zb0HqIxsg3Af4UwnXGrgFL5AcvTgA/K0Sm/YGDA5iSKXXiH5V8qo0QdAvqPHRI3yRJJ6GWSwOWCYX1NibuFuMcsaz3dtF522NYR6VrOLKxKRs3YKxX0M5oMNTut0jg=
